apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9hcmllbHN1YXJlejUzOF9kYl91c2VyOm9rNXE5d29uWUdKOVJjdWtAY2x1c3RlcjAuZmpoeHZtYS5tb25nb2RiLm5ldC8=
