
apiVersion: v1
kind: Service
metadata:
  name: zapatillas-service
spec:
  type: NodePort
  selector:
    app: zapatillas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      nodePort: 30080
